#!/bin/sh

set -eu

script_directory=$(CDPATH='' cd "$(dirname "$0")" && pwd)
repository_root=$(CDPATH='' cd "$script_directory/.." && pwd)
output_path="$repository_root/licenses/tsok.md"
temporary_directory=$(mktemp -d "${TMPDIR:-/tmp}/tsok-licenses.XXXXXX")
trap 'rm -rf "$temporary_directory"' EXIT HUP INT TERM

combined_report="$temporary_directory/licenses.csv"
sorted_report="$temporary_directory/licenses-sorted.csv"
license_tool="$temporary_directory/go-licenses"
: >"$combined_report"

cd "$repository_root"
GOBIN="$temporary_directory" go install github.com/google/go-licenses/v2@v2.0.1
for release_target in linux/amd64 linux/arm64 darwin/amd64 darwin/arm64; do
	release_goos=${release_target%/*}
	release_goarch=${release_target#*/}
	CGO_ENABLED=0 GOOS="$release_goos" GOARCH="$release_goarch" \
		"$license_tool" report ./cmd/tsok \
		--ignore github.com/changhoon-sung/tsok >>"$combined_report"
done

LC_ALL=C sort -u "$combined_report" >"$sorted_report"

{
	printf '%s\n' '<!-- Code generated by scripts/generate-licenses.sh; DO NOT EDIT. -->'
	printf '%s\n\n' '# tsok CLI dependencies'
	printf '%s\n' 'The following open source dependencies are used to build the tsok CLI for'
	printf '%s\n\n' "Linux and macOS on \`amd64\` and \`arm64\`."
	printf '%s\n\n' '## Go packages'
	awk -F, 'NF >= 3 { printf " - [%s](https://pkg.go.dev/%s) ([%s](%s))\n", $1, $1, $3, $2 }' "$sorted_report"
} >"$output_path"
